# Ansible playbook for deploying a Flask app

---
# Install system apt packages
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: update cache
    apt: name=python-software-properties state=present update_cache=yes cache_valid_time=43200
  - name: install packages
    apt: name={{item}} state=installed
    with_items:
      - tree         # Optional
      - python-pip   # Optional
      - python-dev   # Optional
      - python3-pip
      - python3-dev
      - nginx

# Install the app, note: don't do these tasks with become sudo
- hosts: all
  tasks:
  - name: clone repo
    git:
      repo: 'https://github.com/chrisolido/flask-ansible-example.git'
      dest: /root/flask-ansible-example
      update: yes  # Does a git pull if the repo already exists
  - name: install modules in a virtualenv
    pip:
      requirements: /root/flask-ansible-example/requirements.txt
      virtualenv: /root/flask-ansible-example/env
      virtualenv_python: python3.5

# Configure app systemd service and nginx
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: template systemd service config
    copy:
      src: .service
      dest: /etc/systemd/system/flask-ansible-example.service
  - name: start systemd app service
    systemd: name=flask-ansible-example.service state=restarted enabled=yes
  - name: template nginx site config
    template:
      src: .nginx
      dest: /etc/nginx/sites-available/flask-ansible-example
  - name: remove default nginx site config
    file: path=/etc/nginx/sites-enabled/default state=absent
  # - command: mv /etc/nginx/sites-enabled/default /tmp/nginx.sites-enabled.default
  - name: enable nginx site
    file:
      src: /etc/nginx/sites-available/flask-ansible-example
      dest: /etc/nginx/sites-enabled/default
      state: link
      force: yes
  - name: restart nginx
    systemd: name=nginx state=restarted enabled=yes
  - name: open firewall for nginx
    ufw:
      rule: allow
      name: Nginx Full
  - name: Start the flask
    raw: /usr/bin/python /root/flask-ansible-example/app.py &
    become: true
